using MediatR;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Yiodara.Application.Common;
using Yiodara.Application.DTOs;

namespace Yiodara.Application.Features.Country.Query
{
    public class GetCountryByCodeQuery : IRequest<Result<CountryDto>>
    {
        public string? CountryCode { get; set; }
    }

    public class GetCountryByCodeQueryHandler : IRequestHandler<GetCountryByCodeQuery, Result<CountryDto>>
    {
        private readonly List<CountryDto> _countries;

        public GetCountryByCodeQueryHandler()
        {
            #region Countries
            _countries = new List<CountryDto>
            {
                new CountryDto { Code = "AF", Name = "Afghanistan" },
                new CountryDto { Code = "AL", Name = "Albania" },
                new CountryDto { Code = "DZ", Name = "Algeria" },
                new CountryDto { Code = "AD", Name = "Andorra" },
                new CountryDto { Code = "AO", Name = "Angola" },
                new CountryDto { Code = "AG", Name = "Antigua and Barbuda" },
                new CountryDto { Code = "AR", Name = "Argentina" },
                new CountryDto { Code = "AM", Name = "Armenia" },
                new CountryDto { Code = "AU", Name = "Australia" },
                new CountryDto { Code = "AT", Name = "Austria" },
                new CountryDto { Code = "AZ", Name = "Azerbaijan" },
                new CountryDto { Code = "BS", Name = "Bahamas" },
                new CountryDto { Code = "BH", Name = "Bahrain" },
                new CountryDto { Code = "BD", Name = "Bangladesh" },
                new CountryDto { Code = "BB", Name = "Barbados" },
                new CountryDto { Code = "BY", Name = "Belarus" },
                new CountryDto { Code = "BE", Name = "Belgium" },
                new CountryDto { Code = "BZ", Name = "Belize" },
                new CountryDto { Code = "BJ", Name = "Benin" },
                new CountryDto { Code = "BT", Name = "Bhutan" },
                new CountryDto { Code = "BO", Name = "Bolivia" },
                new CountryDto { Code = "BA", Name = "Bosnia and Herzegovina" },
                new CountryDto { Code = "BW", Name = "Botswana" },
                new CountryDto { Code = "BR", Name = "Brazil" },
                new CountryDto { Code = "BN", Name = "Brunei" },
                new CountryDto { Code = "BG", Name = "Bulgaria" },
                new CountryDto { Code = "BF", Name = "Burkina Faso" },
                new CountryDto { Code = "BI", Name = "Burundi" },
                new CountryDto { Code = "CV", Name = "Cabo Verde" },
                new CountryDto { Code = "KH", Name = "Cambodia" },
                new CountryDto { Code = "CM", Name = "Cameroon" },
                new CountryDto { Code = "CA", Name = "Canada" },
                new CountryDto { Code = "CF", Name = "Central African Republic" },
                new CountryDto { Code = "TD", Name = "Chad" },
                new CountryDto { Code = "CL", Name = "Chile" },
                new CountryDto { Code = "CN", Name = "China" },
                new CountryDto { Code = "CO", Name = "Colombia" },
                new CountryDto { Code = "KM", Name = "Comoros" },
                new CountryDto { Code = "CD", Name = "Congo, Democratic Republic of the" },
                new CountryDto { Code = "CG", Name = "Congo, Republic of the" },
                new CountryDto { Code = "CR", Name = "Costa Rica" },
                new CountryDto { Code = "CI", Name = "Côte d'Ivoire" },
                new CountryDto { Code = "HR", Name = "Croatia" },
                new CountryDto { Code = "CU", Name = "Cuba" },
                new CountryDto { Code = "CY", Name = "Cyprus" },
                new CountryDto { Code = "CZ", Name = "Czech Republic" },
                new CountryDto { Code = "DK", Name = "Denmark" },
                new CountryDto { Code = "DJ", Name = "Djibouti" },
                new CountryDto { Code = "DM", Name = "Dominica" },
                new CountryDto { Code = "DO", Name = "Dominican Republic" },
                new CountryDto { Code = "EC", Name = "Ecuador" },
                new CountryDto { Code = "EG", Name = "Egypt" },
                new CountryDto { Code = "SV", Name = "El Salvador" },
                new CountryDto { Code = "GQ", Name = "Equatorial Guinea" },
                new CountryDto { Code = "ER", Name = "Eritrea" },
                new CountryDto { Code = "EE", Name = "Estonia" },
                new CountryDto { Code = "SZ", Name = "Eswatini" },
                new CountryDto { Code = "ET", Name = "Ethiopia" },
                new CountryDto { Code = "FJ", Name = "Fiji" },
                new CountryDto { Code = "FI", Name = "Finland" },
                new CountryDto { Code = "FR", Name = "France" },
                new CountryDto { Code = "GA", Name = "Gabon" },
                new CountryDto { Code = "GM", Name = "Gambia" },
                new CountryDto { Code = "GE", Name = "Georgia" },
                new CountryDto { Code = "DE", Name = "Germany" },
                new CountryDto { Code = "GH", Name = "Ghana" },
                new CountryDto { Code = "GR", Name = "Greece" },
                new CountryDto { Code = "GD", Name = "Grenada" },
                new CountryDto { Code = "GT", Name = "Guatemala" },
                new CountryDto { Code = "GN", Name = "Guinea" },
                new CountryDto { Code = "GW", Name = "Guinea-Bissau" },
                new CountryDto { Code = "GY", Name = "Guyana" },
                new CountryDto { Code = "HT", Name = "Haiti" },
                new CountryDto { Code = "HN", Name = "Honduras" },
                new CountryDto { Code = "HU", Name = "Hungary" },
                new CountryDto { Code = "IS", Name = "Iceland" },
                new CountryDto { Code = "IN", Name = "India" },
                new CountryDto { Code = "ID", Name = "Indonesia" },
                new CountryDto { Code = "IR", Name = "Iran" },
                new CountryDto { Code = "IQ", Name = "Iraq" },
                new CountryDto { Code = "IE", Name = "Ireland" },
                new CountryDto { Code = "IL", Name = "Israel" },
                new CountryDto { Code = "IT", Name = "Italy" },
                new CountryDto { Code = "JM", Name = "Jamaica" },
                new CountryDto { Code = "JP", Name = "Japan" },
                new CountryDto { Code = "JO", Name = "Jordan" },
                new CountryDto { Code = "KZ", Name = "Kazakhstan" },
                new CountryDto { Code = "KE", Name = "Kenya" },
                new CountryDto { Code = "KI", Name = "Kiribati" },
                new CountryDto { Code = "KP", Name = "Korea, North" },
                new CountryDto { Code = "KR", Name = "Korea, South" },
                new CountryDto { Code = "KW", Name = "Kuwait" },
                new CountryDto { Code = "KG", Name = "Kyrgyzstan" },
                new CountryDto { Code = "LA", Name = "Laos" },
                new CountryDto { Code = "LV", Name = "Latvia" },
                new CountryDto { Code = "LB", Name = "Lebanon" },
                new CountryDto { Code = "LS", Name = "Lesotho" },
                new CountryDto { Code = "LR", Name = "Liberia" },
                new CountryDto { Code = "LY", Name = "Libya" },
                new CountryDto { Code = "LI", Name = "Liechtenstein" },
                new CountryDto { Code = "LT", Name = "Lithuania" },
                new CountryDto { Code = "LU", Name = "Luxembourg" },
                new CountryDto { Code = "MG", Name = "Madagascar" },
                new CountryDto { Code = "MW", Name = "Malawi" },
                new CountryDto { Code = "MY", Name = "Malaysia" },
                new CountryDto { Code = "MV", Name = "Maldives" },
                new CountryDto { Code = "ML", Name = "Mali" },
                new CountryDto { Code = "MT", Name = "Malta" },
                new CountryDto { Code = "MH", Name = "Marshall Islands" },
                new CountryDto { Code = "MR", Name = "Mauritania" },
                new CountryDto { Code = "MU", Name = "Mauritius" },
                new CountryDto { Code = "MX", Name = "Mexico" },
                new CountryDto { Code = "FM", Name = "Micronesia" },
                new CountryDto { Code = "MD", Name = "Moldova" },
                new CountryDto { Code = "MC", Name = "Monaco" },
                new CountryDto { Code = "MN", Name = "Mongolia" },
                new CountryDto { Code = "ME", Name = "Montenegro" },
                new CountryDto { Code = "MA", Name = "Morocco" },
                new CountryDto { Code = "MZ", Name = "Mozambique" },
                new CountryDto { Code = "MM", Name = "Myanmar" },
                new CountryDto { Code = "NA", Name = "Namibia" },
                new CountryDto { Code = "NR", Name = "Nauru" },
                new CountryDto { Code = "NP", Name = "Nepal" },
                new CountryDto { Code = "NL", Name = "Netherlands" },
                new CountryDto { Code = "NZ", Name = "New Zealand" },
                new CountryDto { Code = "NI", Name = "Nicaragua" },
                new CountryDto { Code = "NE", Name = "Niger" },
                new CountryDto { Code = "NG", Name = "Nigeria" },
                new CountryDto { Code = "MK", Name = "North Macedonia" },
                new CountryDto { Code = "NO", Name = "Norway" },
                new CountryDto { Code = "OM", Name = "Oman" },
                new CountryDto { Code = "PK", Name = "Pakistan" },
                new CountryDto { Code = "PW", Name = "Palau" },
                new CountryDto { Code = "PS", Name = "Palestine" },
                new CountryDto { Code = "PA", Name = "Panama" },
                new CountryDto { Code = "PG", Name = "Papua New Guinea" },
                new CountryDto { Code = "PY", Name = "Paraguay" },
                new CountryDto { Code = "PE", Name = "Peru" },
                new CountryDto { Code = "PH", Name = "Philippines" },
                new CountryDto { Code = "PL", Name = "Poland" },
                new CountryDto { Code = "PT", Name = "Portugal" },
                new CountryDto { Code = "QA", Name = "Qatar" },
                new CountryDto { Code = "RO", Name = "Romania" },
                new CountryDto { Code = "RU", Name = "Russia" },
                new CountryDto { Code = "RW", Name = "Rwanda" },
                new CountryDto { Code = "KN", Name = "Saint Kitts and Nevis" },
                new CountryDto { Code = "LC", Name = "Saint Lucia" },
                new CountryDto { Code = "VC", Name = "Saint Vincent and the Grenadines" },
                new CountryDto { Code = "WS", Name = "Samoa" },
                new CountryDto { Code = "SM", Name = "San Marino" },
                new CountryDto { Code = "ST", Name = "Sao Tome and Principe" },
                new CountryDto { Code = "SA", Name = "Saudi Arabia" },
                new CountryDto { Code = "SN", Name = "Senegal" },
                new CountryDto { Code = "RS", Name = "Serbia" },
                new CountryDto { Code = "SC", Name = "Seychelles" },
                new CountryDto { Code = "SL", Name = "Sierra Leone" },
                new CountryDto { Code = "SG", Name = "Singapore" },
                new CountryDto { Code = "SK", Name = "Slovakia" },
                new CountryDto { Code = "SI", Name = "Slovenia" },
                new CountryDto { Code = "SB", Name = "Solomon Islands" },
                new CountryDto { Code = "SO", Name = "Somalia" },
                new CountryDto { Code = "ZA", Name = "South Africa" },
                new CountryDto { Code = "SS", Name = "South Sudan" },
                new CountryDto { Code = "ES", Name = "Spain" },
                new CountryDto { Code = "LK", Name = "Sri Lanka" },
                new CountryDto { Code = "SD", Name = "Sudan" },
                new CountryDto { Code = "SR", Name = "Suriname" },
                new CountryDto { Code = "SE", Name = "Sweden" },
                new CountryDto { Code = "CH", Name = "Switzerland" },
                new CountryDto { Code = "SY", Name = "Syria" },
                new CountryDto { Code = "TW", Name = "Taiwan" },
                new CountryDto { Code = "TJ", Name = "Tajikistan" },
                new CountryDto { Code = "TZ", Name = "Tanzania" },
                new CountryDto { Code = "TH", Name = "Thailand" },
                new CountryDto { Code = "TL", Name = "Timor-Leste" },
                new CountryDto { Code = "TG", Name = "Togo" },
                new CountryDto { Code = "TO", Name = "Tonga" },
                new CountryDto { Code = "TT", Name = "Trinidad and Tobago" },
                new CountryDto { Code = "TN", Name = "Tunisia" },
                new CountryDto { Code = "TR", Name = "Turkey" },
                new CountryDto { Code = "TM", Name = "Turkmenistan" },
                new CountryDto { Code = "TV", Name = "Tuvalu" },
                new CountryDto { Code = "UG", Name = "Uganda" },
                new CountryDto { Code = "UA", Name = "Ukraine" },
                new CountryDto { Code = "AE", Name = "United Arab Emirates" },
                new CountryDto { Code = "GB", Name = "United Kingdom" },
                new CountryDto { Code = "US", Name = "United States" },
                new CountryDto { Code = "UY", Name = "Uruguay" },
                new CountryDto { Code = "UZ", Name = "Uzbekistan" },
                new CountryDto { Code = "VU", Name = "Vanuatu" },
                new CountryDto { Code = "VA", Name = "Vatican City" },
                new CountryDto { Code = "VE", Name = "Venezuela" },
                new CountryDto { Code = "VN", Name = "Vietnam" },
                new CountryDto { Code = "YE", Name = "Yemen" },
                new CountryDto { Code = "ZM", Name = "Zambia" },
                new CountryDto { Code = "ZW", Name = "Zimbabwe" }
            };
            #endregion
        }

        public async Task<Result<CountryDto>> Handle(GetCountryByCodeQuery request, CancellationToken cancellationToken)
        {
            var country = _countries.FirstOrDefault(c => c.Code.Equals(request.CountryCode, StringComparison.OrdinalIgnoreCase));

            if (country == null)
                return Result<CountryDto>.Failure($"Country with code '{request.CountryCode}' not found.");

            return Result<CountryDto>.Success(country);
        }
    }
}